"""Add videos, comments, playlists & filters

Revision ID: b03b535d72b0
Revises: ffdc0a98111c
Create Date: 2025-08-10 06:19:21.804353

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")
if SCHEMA:
    SCHEMA = SCHEMA.lower()


# revision identifiers, used by Alembic.
revision = 'b03b535d72b0'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('playlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playlist_videos',
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('playlist_id', 'video_id')
    )
    # op.create_table('video_filters',
    # sa.Column('video_id', sa.Integer(), nullable=False),
    # sa.Column('filter_id', sa.Integer(), nullable=False),
    # sa.ForeignKeyConstraint(['filter_id'], ['filters.id'], ),
    # sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    # sa.PrimaryKeyConstraint('video_id', 'filter_id')
    # )
    op.add_column('users', sa.Column('first_name', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=50), nullable=True))
    
    if environment == "production":
        # Only execute PostgreSQL-specific commands for PostgreSQL
        bind = op.get_bind()
        if bind.dialect.name == 'postgresql':
            op.execute(f"ALTER TABLE filters SET SCHEMA {SCHEMA};")
            op.execute(f"ALTER TABLE playlists SET SCHEMA {SCHEMA};")
            op.execute(f"ALTER TABLE videos SET SCHEMA {SCHEMA};")
            op.execute(f"ALTER TABLE comments SET SCHEMA {SCHEMA};")
            op.execute(f"ALTER TABLE playlist_videos SET SCHEMA {SCHEMA};")
            op.execute(f"ALTER TABLE video_filters SET SCHEMA {SCHEMA};")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_table('video_filters')
    op.drop_table('playlist_videos')
    op.drop_table('comments')
    op.drop_table('videos')
    op.drop_table('playlists')
    op.drop_table('filters')
    # ### end Alembic commands ###
