"""Add comment_id to videos table

Revision ID: 03bc19ff927d
Revises: 56ea99591266
Create Date: 2025-08-23 11:10:00.316131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03bc19ff927d'
down_revision = '56ea99591266'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_videos_comment_id_comments', 'comments', ['comment_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_constraint('fk_videos_comment_id_comments', type_='foreignkey')
        batch_op.drop_column('comment_id')

    # ### end Alembic commands ###
